version: '2'
services:
    21points-app:
        image: 21points
        external_links:
            - 21points-mysql:mysql
            - 21points-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/21points?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    21points-mysql:
        extends:
            file: mysql.yml
            service: 21points-mysql
    21points-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: 21points-elasticsearch
